// ═══════════════════════════════════════════════════════════════════════════
// QUESTIONS DIAGNOSTIQUES — 10 questions ancrées sur les normes
// Ce fichier est importé côté front (affichage) ET côté API (validation).
// ═══════════════════════════════════════════════════════════════════════════

export const QUESTIONS = [
  {
    id: "nom", type: "text", section: "Profil",
    icone: "🏗️", titre: "Faisons connaissance",
    question: "Quel est le nom de votre entreprise ?",
    placeholder: "Ex : Entreprise Martin BTP",
    pourquoi: "Personnalise l'intégralité du tableau de bord.",
    normes: [], indicateur: "Identification du rapport RSE",
  },
  {
    id: "taille", type: "choix", section: "Profil",
    icone: "👥", titre: "Votre structure",
    question: "Combien de salariés compte votre entreprise ?",
    pourquoi: "La taille détermine vos obligations légales : CSE (>11), index F/H (>50), DPEF (>500), CSRD (progressive). Référence : Code du travail & directive CSRD.",
    normes: ["ESRS_G1", "ISO26000"],
    indicateur: "Seuils réglementaires applicables",
    options: [
      { v: "micro", l: "< 10 salariés",   s: "Artisan / auto-entrepreneur",    e: "🔧" },
      { v: "tpe",   l: "10 – 49",          s: "TPE — seuil CSE à surveiller",   e: "🏠" },
      { v: "pme50", l: "50 – 249",         s: "PME — index F/H obligatoire",    e: "🏢" },
      { v: "pme250",l: "250 et plus",      s: "ETI — DPEF & CSRD en approche",  e: "🏭" },
    ],
  },
  {
    id: "activite", type: "multi", section: "Profil",
    icone: "⚒️", titre: "Votre cœur de métier",
    question: "Quelles activités exercez-vous principalement ?",
    pourquoi: "L'activité détermine votre empreinte carbone (Scopes 1/2/3), vos flux de déchets réglementés et les risques professionnels prioritaires.",
    normes: ["GRI_E", "GRI_W", "SNBC", "RE2020"],
    indicateur: "Facteurs d'émission Scope 1/2/3, flux déchets, risques métier",
    options: [
      { v: "gros_oeuvre",    l: "Gros œuvre",           e: "🧱" },
      { v: "second_oeuvre",  l: "Second œuvre",          e: "🪟" },
      { v: "genie_civil",    l: "Génie civil / TP",      e: "🛣️" },
      { v: "renovation",     l: "Rénovation / réhab",    e: "🔨" },
      { v: "demolition",     l: "Démolition",             e: "💥" },
      { v: "elec_cvc",       l: "Électricité / CVC",     e: "⚡" },
    ],
  },
  {
    id: "chantiers_nb", type: "choix", section: "Profil",
    icone: "📋", titre: "Volume d'activité",
    question: "Combien de chantiers actifs gérez-vous simultanément ?",
    pourquoi: "Volume = complexité de standardisation des pratiques HSE et de traçabilité des déchets.",
    normes: ["ISO26000", "GRI_W", "GRI_OHS"],
    indicateur: "Taux de conformité HSE multi-sites, kg déchets/m² agrégés",
    options: [
      { v: "1_3",   l: "1 à 3",     s: "Gestion directe possible",       e: "🎯" },
      { v: "4_10",  l: "4 à 10",    s: "Coordination nécessaire",        e: "📊" },
      { v: "11_30", l: "11 à 30",   s: "Standardisation indispensable",  e: "🔄" },
      { v: "30p",   l: "Plus de 30",s: "Système de management requis",   e: "🏗️" },
    ],
  },
  {
    id: "dechets_pratique", type: "choix", section: "Environnement",
    icone: "♻️", titre: "Gestion des déchets",
    question: "Comment gérez-vous actuellement vos déchets de chantier ?",
    pourquoi: "Obligation légale : tri à la source (7 flux depuis 2022, Loi AGEC). Diagnostic PEMD obligatoire avant démolition >1000m².",
    normes: ["GRI_W", "AGEC", "PEMD", "REP_PMCB", "ESRS_E5"],
    indicateur: "Taux valorisation déchets (%), kg déchets/m²",
    options: [
      { v: "aucun",      l: "Pas de tri organisé",     s: "Benne unique, pas de suivi",            e: "⚠️" },
      { v: "partiel",    l: "Tri partiel",              s: "Quelques flux séparés, sans tracé BSD", e: "📦" },
      { v: "7flux",      l: "Tri 7 flux + BSD",         s: "Conformité AGEC atteinte",              e: "✅" },
      { v: "optimise",   l: "Démarche optimisée",       s: "Diagnostic PEMD + filières valorisation", e: "🏆" },
    ],
  },
  {
    id: "carbone_bilan", type: "choix", section: "Environnement",
    icone: "🌡️", titre: "Empreinte carbone",
    question: "Avez-vous réalisé un bilan de vos émissions de gaz à effet de serre ?",
    pourquoi: "Le BTP représente ~25% des émissions françaises (SNBC). La CSRD rend le reporting Scope 1/2/3 progressivement obligatoire.",
    normes: ["GRI_E", "ESRS_E1", "SNBC", "RE2020"],
    indicateur: "tCO₂e/k€ CA, tCO₂e/m² construit (Scopes 1+2+3)",
    options: [
      { v: "jamais",     l: "Jamais réalisé",          s: "Pas d'estimation disponible",              e: "❓" },
      { v: "partiel",    l: "Estimation partielle",     s: "Scope 1 carburant seulement",              e: "📐" },
      { v: "complet",    l: "Bilan GES complet",        s: "Scopes 1+2+3, méthode ADEME",              e: "📊" },
      { v: "certifie",   l: "Bilan certifié + plan",    s: "Bilan Carbone® + objectifs de réduction",  e: "🌱" },
    ],
  },
  {
    id: "securite_niveau", type: "choix", section: "Social",
    icone: "🦺", titre: "Sécurité au travail",
    question: "Quel est votre niveau de maturité en santé-sécurité au travail ?",
    pourquoi: "Le BTP est le 2ème secteur le plus accidentogène. L'employeur a une obligation de résultat (Code du travail L.4121-1).",
    normes: ["CT_L4121", "GRI_OHS", "ESRS_S1", "ISO26000"],
    indicateur: "Taux de Fréquence (TF), Taux de Gravité (TG), conformité DUERP",
    options: [
      { v: "minimal",    l: "Obligations minimales",   s: "DUERP existant, peu mis à jour",           e: "📄" },
      { v: "actif",      l: "Prévention active",        s: "PPSPS systématique, causerie sécurité",    e: "🦺" },
      { v: "mase",       l: "Démarche MASE engagée",   s: "Manuel MASE en cours de déploiement",      e: "📋" },
      { v: "certifie",   l: "Certifié ISO 45001/MASE",s: "Système de management SST opérationnel",   e: "🏆" },
    ],
  },
  {
    id: "formation_rh", type: "choix", section: "Social",
    icone: "📚", titre: "Formation & compétences",
    question: "Comment pilotez-vous la formation de vos équipes ?",
    pourquoi: "Droit individuel à la formation (Code travail L.6311-1). GRI 404 mesure les heures de formation/ETP/an.",
    normes: ["CT_L6311", "GRI_T", "ESRS_S1"],
    indicateur: "Heures formation/salarié/an, taux d'alternance, budget formation (% MS)",
    options: [
      { v: "obligation",  l: "Formations obligatoires seules", s: "CACES, habilitations, SST uniquement",     e: "🔖" },
      { v: "plan",        l: "Plan de formation structuré",    s: "PDC annuel, CPF accompagné",               e: "📅" },
      { v: "proactif",    l: "Démarche proactive",             s: "CQP BTP, alternance, parcours carrière",   e: "🎓" },
      { v: "GPEC",        l: "GPEC & compétences stratégiques",s: "Gestion prévisionnelle, plan 3 ans",       e: "🌟" },
    ],
  },
  {
    id: "gouvernance_achats", type: "choix", section: "Gouvernance",
    icone: "🔗", titre: "Achats responsables",
    question: "Comment intégrez-vous la RSE dans vos achats et sous-traitance ?",
    pourquoi: "ISO 26000 §6.6 : loyauté des pratiques. La loi LME impose 60j de délai de paiement.",
    normes: ["ISO26000", "LME", "ESRS_G1"],
    indicateur: "Délai paiement fournisseurs (j), % sous-traitants évalués RSE",
    options: [
      { v: "prix_seul",   l: "Critère prix uniquement",     s: "Pas d'évaluation RSE fournisseurs",       e: "💰" },
      { v: "clause",      l: "Clauses contractuelles RSE",  s: "Charte ou annexe RSE dans les contrats",  e: "📃" },
      { v: "evaluation",  l: "Évaluation structurée",       s: "Grille RSE, EcoVadis ou QUALIBAT exigé",  e: "📊" },
      { v: "partenariat", l: "Partenariat RSE actif",       s: "Co-construction de progrès avec fournisseurs", e: "🤝" },
    ],
  },
  {
    id: "reporting_transparence", type: "choix", section: "Gouvernance",
    icone: "📊", titre: "Transparence & reporting",
    question: "Communiquez-vous sur votre performance RSE ?",
    pourquoi: "CSRD (2024-2028) étend progressivement l'obligation de reporting ESG. DPEF obligatoire >500 salariés.",
    normes: ["ESRS_G1", "ISO26000", "GRI_E"],
    indicateur: "Niveau CSRD-readiness, score GRI, indicateurs ESRS publiés",
    options: [
      { v: "aucun",       l: "Aucune communication RSE",   s: "Pas de rapport ni de section dédiée",         e: "🔇" },
      { v: "interne",     l: "Reporting interne uniquement",s: "Indicateurs suivis, non publiés",             e: "📁" },
      { v: "voluntaire",  l: "Rapport RSE volontaire",      s: "Publié sur site web ou pour appels d'offres", e: "📢" },
      { v: "certifie",    l: "Reporting certifié / CSRD",   s: "Selon GRI Standards ou normes ESRS",          e: "🏅" },
    ],
  },
];

// Preset démo pour le bouton "Remplissage rapide"
export const DEMO_PRESET = {
  nom: "Entreprise Dupont BTP",
  taille: "pme50",
  activite: ["gros_oeuvre", "second_oeuvre", "renovation"],
  chantiers_nb: "4_10",
  dechets_pratique: "partiel",
  carbone_bilan: "partiel",
  securite_niveau: "actif",
  formation_rh: "plan",
  gouvernance_achats: "clause",
  reporting_transparence: "interne",
};
